//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agents.Data
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agents()
        {
            this.Realisation = new HashSet<Realisation>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Director { get; set; }
        public string TaxNumber { get; set; }
        public string CodeRegistration { get; set; }
        public int Discount
        {
            get
            {
                decimal sum = Realisation.Sum(s => s.Quantity * s.Products.MinimumPrice);
                if (sum < 10000) return 0;
                if (sum >= 10000 && sum < 50000) return 5;
                if (sum >= 50000 && sum < 150000) return 10;
                if (sum >= 150000 && sum < 500000) return 20;
                return 25;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Realisation> Realisation { get; set; }
    }
}
