//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Data.Entity.Infrastructure;
using System.Data.Entity;

public partial class PleasantRustleEntities : DbContext
{
    static private PleasantRustleEntities dataBase;

    public PleasantRustleEntities()
        : base("name=PleasantRustleEntities")
    {
    }

    static public PleasantRustleEntities GetContext()
    {
        if(dataBase == null)
            dataBase = new PleasantRustleEntities();

        return dataBase;
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Agents.Data.Agents> Agents { get; set; }
    public virtual DbSet<Agents.Data.Products> Products { get; set; }
    public virtual DbSet<Agents.Data.Realisation> Realisation { get; set; }
}
